export * from './airQualityForecast.service';
import { AirQualityForecastService } from './airQualityForecast.service';
export * from './alerts.service';
import { AlertsService } from './alerts.service';
export * from './bulkDownloads.service';
import { BulkDownloadsService } from './bulkDownloads.service';
export * from './class120HourHourlyForecast.service';
import { Class120HourHourlyForecastService } from './class120HourHourlyForecast.service';
export * from './class16DayDailyForecast.service';
import { Class16DayDailyForecastService } from './class16DayDailyForecast.service';
export * from './class5Day3HourForecast.service';
import { Class5Day3HourForecastService } from './class5Day3HourForecast.service';
export * from './currentAirQuality.service';
import { CurrentAirQualityService } from './currentAirQuality.service';
export * from './currentWeatherData.service';
import { CurrentWeatherDataService } from './currentWeatherData.service';
export * from './dailyHistoricalWeatherData.service';
import { DailyHistoricalWeatherDataService } from './dailyHistoricalWeatherData.service';
export * from './forecastDegreeDayAPI.service';
import { ForecastDegreeDayAPIService } from './forecastDegreeDayAPI.service';
export * from './forecastSolarIrradianceAPI.service';
import { ForecastSolarIrradianceAPIService } from './forecastSolarIrradianceAPI.service';
export * from './historicalAirQuality.service';
import { HistoricalAirQualityService } from './historicalAirQuality.service';
export * from './historicalDegreeDayAPI.service';
import { HistoricalDegreeDayAPIService } from './historicalDegreeDayAPI.service';
export * from './historicalSolarIrradianceAPI.service';
import { HistoricalSolarIrradianceAPIService } from './historicalSolarIrradianceAPI.service';
export * from './historicalWeatherEnergyAPI.service';
import { HistoricalWeatherEnergyAPIService } from './historicalWeatherEnergyAPI.service';
export * from './hourlyHistoricalWeatherData.service';
import { HourlyHistoricalWeatherDataService } from './hourlyHistoricalWeatherData.service';
export const APIS = [AirQualityForecastService, AlertsService, BulkDownloadsService, Class120HourHourlyForecastService, Class16DayDailyForecastService, Class5Day3HourForecastService, CurrentAirQualityService, CurrentWeatherDataService, DailyHistoricalWeatherDataService, ForecastDegreeDayAPIService, ForecastSolarIrradianceAPIService, HistoricalAirQualityService, HistoricalDegreeDayAPIService, HistoricalSolarIrradianceAPIService, HistoricalWeatherEnergyAPIService, HourlyHistoricalWeatherDataService];
