# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NewUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, login: str=None, password: str=None):  # noqa: E501
        """NewUser - a model defined in Swagger

        :param login: The login of this NewUser.  # noqa: E501
        :type login: str
        :param password: The password of this NewUser.  # noqa: E501
        :type password: str
        """
        self.swagger_types = {
            'login': str,
            'password': str
        }

        self.attribute_map = {
            'login': 'login',
            'password': 'password'
        }
        self._login = login
        self._password = password

    @classmethod
    def from_dict(cls, dikt) -> 'NewUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewUser of this NewUser.  # noqa: E501
        :rtype: NewUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def login(self) -> str:
        """Gets the login of this NewUser.

        The uniqe login of the user  # noqa: E501

        :return: The login of this NewUser.
        :rtype: str
        """
        return self._login

    @login.setter
    def login(self, login: str):
        """Sets the login of this NewUser.

        The uniqe login of the user  # noqa: E501

        :param login: The login of this NewUser.
        :type login: str
        """
        if login is None:
            raise ValueError("Invalid value for `login`, must not be `None`")  # noqa: E501

        self._login = login

    @property
    def password(self) -> str:
        """Gets the password of this NewUser.

        Password of the user  # noqa: E501

        :return: The password of this NewUser.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this NewUser.

        Password of the user  # noqa: E501

        :param password: The password of this NewUser.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password
