# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class NewBroadcastMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, contents: str=None):  # noqa: E501
        """NewBroadcastMessage - a model defined in Swagger

        :param contents: The contents of this NewBroadcastMessage.  # noqa: E501
        :type contents: str
        """
        self.swagger_types = {
            'contents': str
        }

        self.attribute_map = {
            'contents': 'contents'
        }
        self._contents = contents

    @classmethod
    def from_dict(cls, dikt) -> 'NewBroadcastMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewBroadcastMessage of this NewBroadcastMessage.  # noqa: E501
        :rtype: NewBroadcastMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contents(self) -> str:
        """Gets the contents of this NewBroadcastMessage.

        Proper contents of the message  # noqa: E501

        :return: The contents of this NewBroadcastMessage.
        :rtype: str
        """
        return self._contents

    @contents.setter
    def contents(self, contents: str):
        """Sets the contents of this NewBroadcastMessage.

        Proper contents of the message  # noqa: E501

        :param contents: The contents of this NewBroadcastMessage.
        :type contents: str
        """
        if contents is None:
            raise ValueError("Invalid value for `contents`, must not be `None`")  # noqa: E501

        self._contents = contents
