/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrentObsWeather } from './currentObsWeather';


export interface CurrentObs { 
    /**
     * City name (closest)
     */
    city_name?: string;
    /**
     * State abbreviation
     */
    state_code?: string;
    /**
     * Country abbreviation
     */
    country_code?: string;
    /**
     * Local IANA time zone
     */
    timezone?: string;
    /**
     * Latitude
     */
    lat?: number;
    /**
     * Longitude
     */
    lon?: number;
    /**
     * Source Station ID
     */
    station?: string;
    /**
     * Visibility - default (M)
     */
    vis?: number;
    /**
     * Relative humidity (%)
     */
    rh?: number;
    /**
     * Dew point temperature - default (C)
     */
    dewpt?: number;
    /**
     * Wind direction (degrees)
     */
    wind_dir?: number;
    /**
     * Cardinal wind direction
     */
    wind_cdir?: string;
    /**
     * Cardinal wind direction (text)
     */
    wind_cdir_full?: string;
    /**
     * Wind speed - Default (m/s)
     */
    wind_speed?: number;
    /**
     * Temperature - Default (C)
     */
    temp?: number;
    /**
     * Apparent temperature - Default (C)
     */
    app_temp?: number;
    /**
     * Cloud cover (%)
     */
    clouds?: number;
    weather?: CurrentObsWeather;
    /**
     * Cycle Hour (UTC) of observation
     */
    datetime?: string;
    /**
     * Full time (UTC) of observation (YYYY-MM-DD HH:MM)
     */
    ob_time?: string;
    /**
     * Unix Timestamp
     */
    ts?: number;
    /**
     * Time (UTC) of Sunrise (HH:MM)
     */
    sunrise?: string;
    /**
     * Time (UTC) of Sunset (HH:MM)
     */
    sunset?: string;
    /**
     * Mean sea level pressure in millibars (mb)
     */
    slp?: number;
    /**
     * Pressure (mb)
     */
    pres?: number;
    /**
     * Air quality index (US EPA standard 0 to +500)
     */
    aqi?: number;
    /**
     * UV Index
     */
    uv?: number;
    /**
     * Estimated solar radiation (W/m^2)
     */
    solar_rad?: number;
    /**
     * Global horizontal irradiance (W/m^2)
     */
    ghi?: number;
    /**
     * Direct normal irradiance (W/m^2)
     */
    dni?: number;
    /**
     * Diffuse horizontal irradiance (W/m^2)
     */
    dhi?: number;
    /**
     * Current solar elevation angle (Degrees)
     */
    elev_angle?: number;
    /**
     * Current solar hour angle (Degrees)
     */
    hour_angle?: number;
    /**
     * Part of the day (d = day, n = night)
     */
    pod?: string;
    /**
     * Precipitation in last hour - Default (mm)
     */
    precip?: number;
    /**
     * Snowfall in last hour - Default (mm)
     */
    snow?: number;
}

