/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeoIPObj { 
    /**
     * City Name
     */
    longitude?: string;
    /**
     * State Abbreviation
     */
    latitude?: string;
    /**
     * UTC Offset (deprecated)
     */
    offset?: string;
    /**
     * Local IANA time zone
     */
    timezone?: string;
    /**
     * Organization Name
     */
    organization?: string;
    /**
     * Country Abbreviation
     */
    continent_code?: string;
    /**
     * Latitude
     */
    region?: string;
    /**
     * Longitude
     */
    metro_code?: string;
    /**
     * Longitude
     */
    dma_code?: string;
    /**
     * IP Address
     */
    ip?: string;
    /**
     * Country Code (Short)
     */
    country_code?: string;
    /**
     * Area Code
     */
    area_code?: string;
    /**
     * Postal Code
     */
    postal_code?: string;
    /**
     * Character encoding
     */
    charset?: string;
    /**
     * City Name
     */
    city?: string;
    /**
     * Country Code (Long)
     */
    country_code3?: string;
}

