/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoryDayObj { 
    /**
     * Date in format \"YYYY-MM-DD\". All datetime is in (UTC)
     */
    datetime?: string;
    /**
     * Unix timestamp of datetime (Midnight UTC)
     */
    ts?: number;
    /**
     * Average sea level pressure (mb)
     */
    slp?: number;
    /**
     * Average pressure (mb)
     */
    pres?: number;
    /**
     * Average relative humidity as a percentage (%)
     */
    rh?: number;
    /**
     * Average dewpoint - Default (C)
     */
    dewpt?: number;
    /**
     * Average temperature - Default (C)
     */
    temp?: number;
    /**
     * Max temperature - Default (C)
     */
    max_temp?: number;
    /**
     * Time of max memperature - Unix Timestamp
     */
    max_temp_ts?: number;
    /**
     * Min temperature - Default (C)
     */
    min_temp?: number;
    /**
     * Time of max temperature - unix timestamp
     */
    min_temp_ts?: number;
    /**
     * Average wind speed - default (m/s)
     */
    wind_spd?: number;
    /**
     * Average wind direction (degrees)
     */
    wind_dir?: number;
    /**
     * Wind gust speed - default (m/s)
     */
    wind_gust_spd?: number;
    /**
     * Max 2min Wind Speed - default (m/s)
     */
    max_wind_spd?: number;
    /**
     * Direction of wind at time of max 2min wind (degrees)
     */
    max_wind_dir?: number;
    /**
     * Time of max 2min wind - unix timestamp
     */
    max_wind_spd_ts?: number;
    /**
     * Average hourly global horizontal solar irradiance (W/m^2)
     */
    ghi?: number;
    /**
     * Total global horizontal solar irradiance (W/m^2)
     */
    t_ghi?: number;
    /**
     * Average direct normal solar irradiance (W/m^2)
     */
    dni?: number;
    /**
     * Total direct normal solar irradiance (W/m^2)
     */
    t_dni?: number;
    /**
     * Average hourly diffuse horizontal solar irradiance (W/m^2)
     */
    dhi?: number;
    /**
     * Total diffuse horizontal solar irradiance (W/m^2)
     */
    t_dhi?: number;
    /**
     * Max UV Index (1-11+)
     */
    max_uv?: number;
    /**
     * Liquid equivalent precipitation - default (mm)
     */
    precip?: number;
    /**
     * Satellite estimated liquid equivalent precipitation - default (mm)
     */
    precip_gpm?: number;
    /**
     * Snowfall - default (mm)
     */
    snow?: number;
    /**
     * Snow Depth - default (mm)
     */
    snow_depth?: number;
}

