/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoryObjWeather } from './historyObjWeather';


export interface HistoryObj { 
    /**
     * Unix Timestamp
     */
    ts?: number;
    /**
     * Timestamp in local time
     */
    timestamp_local?: string;
    /**
     * Timestamp UTC
     */
    timestamp_utc?: string;
    /**
     * Date in format \"YYYY-MM-DD:HH\". All datetime is in (UTC)
     */
    datetime?: string;
    /**
     * Sea level pressure (mb)
     */
    slp?: number;
    /**
     * Pressure (mb)
     */
    pres?: number;
    /**
     * Relative Humidity as a percentage (%)
     */
    rh?: number;
    /**
     * Dew point (Default Celcius)
     */
    dewpt?: number;
    /**
     * Temperature (Default Celcius)
     */
    temp?: number;
    /**
     * Wind Speed (Default m/s)
     */
    wind_spd?: number;
    /**
     * Wind direction (Degrees)
     */
    wind_dir?: number;
    /**
     * UV Index (1-11+)
     */
    uv?: number;
    /**
     * Estimated solar radiation (W/m^2)
     */
    solar_rad?: number;
    /**
     * Global horizontal solar irradiance (W/m^2)
     */
    ghi?: number;
    /**
     * Diffuse normal solar irradiance (W/m^2)
     */
    dhi?: number;
    /**
     * Direct normal solar irradiance (W/m^2)
     */
    dni?: number;
    /**
     * Solar hour angle (Degrees)
     */
    h_angle?: number;
    /**
     * Solar elevation angle (Degrees)
     */
    elev_angle?: number;
    /**
     * Part of the day (d = day, n = night)
     */
    pod?: string;
    weather?: HistoryObjWeather;
    /**
     * Liquid equivalent precipitation - Default (mm)
     */
    precip?: number;
    /**
     * Snowfall - Default (mm)
     */
    snow?: number;
    /**
     * Snowfall in last 6 hours - Default (mm)
     */
    snow6h?: number;
}

