/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WeatherAlertGroup { 
    /**
     * Brief description of weather alert
     */
    title?: string;
    /**
     * Full description of weather alert
     */
    description?: string;
    /**
     * Severity of weather. (Advisory | Watch | Warning)
     */
    severity?: string;
    /**
     * Issued time UTC
     */
    effective_utc?: string;
    /**
     * Issued time local
     */
    effective_local?: string;
    /**
     * Expiration time UTC
     */
    expires_utc?: string;
    /**
     * Expiration time local
     */
    expires_local?: string;
    /**
     * URI to weather alert
     */
    uri?: string;
    alerts?: Array<string>;
}

